/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_rh;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frm_ferias extends javax.swing.JFrame {

    /**
     * Creates new form frm_ferias
     */
    public frm_ferias() {
        initComponents();
    }

    
    private final List<Cls_Ferias> lista_ferias_funcionarios = new ArrayList<Cls_Ferias>();
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        txt_tempo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCalcularFerias = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_resultado = new javax.swing.JTextArea();
        btn_VoltarFerias = new javax.swing.JButton();
        txt_salarioBruto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 51, 51));
        setIconImages(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Férias");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Matrícula");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Dias de Férias");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnCalcularFerias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalcularFerias.setText("Calcular Férias");
        btnCalcularFerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularFeriasActionPerformed(evt);
            }
        });

        txt_resultado.setColumns(20);
        txt_resultado.setRows(5);
        jScrollPane1.setViewportView(txt_resultado);

        btn_VoltarFerias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_VoltarFerias.setText("Voltar");
        btn_VoltarFerias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarFeriasActionPerformed(evt);
            }
        });

        jLabel5.setText("Salário Bruto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_matricula, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txt_tempo)
                            .addComponent(txt_salarioBruto))))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnCalcularFerias))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btn_VoltarFerias)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_salarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCalcularFerias)
                .addGap(18, 18, 18)
                .addComponent(btn_VoltarFerias)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnCalcularFeriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularFeriasActionPerformed
        Cls_Ferias feriasFunc = new Cls_Ferias();
        
        feriasFunc.setMatricula(Integer.parseInt(txt_matricula.getText()));
         
          feriasFunc.setSalarioBruto(Double.parseDouble(txt_salarioBruto.getText()));
           
           // ferias - sao 30 dias
           int feriasAcurtir = feriasFunc.getTempoFerias();
           
           System.out.println(feriasAcurtir);
           
           int tempoDesejado = Integer.parseInt(txt_tempo.getText());
           
           if(tempoDesejado > 30 || tempoDesejado > feriasAcurtir){
               JOptionPane.showMessageDialog(null, " Atenção, tempo desejado incompatível !!");
               txt_tempo.setText("");
           } else{
               feriasFunc.setTempoFerias(feriasAcurtir-tempoDesejado);
           }
            
           // metade do salario para 15 dias 
           // salario * tempoDesejado
           //Valor base = (Salário bruto + Média de hora extra) / 30 x Dias de férias usufruídas
           double valorBase = (feriasFunc.getSalarioBruto() / 30) * tempoDesejado;
           
           System.out.println(valorBase);
           
           double totalProventos = valorBase + (valorBase / 3);
           
           feriasFunc.setTotalProventos(Math.floor(totalProventos));
           
           String resultado = " \n Calculo de férias de Funcionario \n " 
                              +"\n Matricula : " + feriasFunc.getMatricula() 
                              +"\n Ferias a Curtir : " + feriasFunc.getTempoFerias()
                              +"\n Tempo desejado : " + tempoDesejado
                              +"\n Total proventos : " + feriasFunc.getTotalProventos();
           
           txt_resultado.setText(resultado);
    }//GEN-LAST:event_btnCalcularFeriasActionPerformed

    private void btn_VoltarFeriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarFeriasActionPerformed
        new frm_Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VoltarFeriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ferias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ferias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ferias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ferias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ferias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularFerias;
    private javax.swing.JButton btn_VoltarFerias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_matricula;
    private javax.swing.JTextArea txt_resultado;
    private javax.swing.JTextField txt_salarioBruto;
    private javax.swing.JTextField txt_tempo;
    // End of variables declaration//GEN-END:variables
}
